### ISSUE TITLE
Turn visualization only works properly if no other turn is made within (length) turns.

### ISSUE THREAD

**Issue by elliotel** [elliotel/chipKIT-uC32-snake#4]
Since the counter movesSinceTurn has to reach the length of the snake for move() to correctly display the last couple pixels of the snake turning, turning again before then (and thereby resetting the counter) will make them display improperly.

A suggestion for a solution (that I will try to implement once I fix the other display bug (#2), is to store multiple turn counters, in something similar to a small queue. While it does seem a bit overkill, it is the simplest solution I can come up with at the moment (but will try to rethink later)

**Comment by Fetaost-code** [comment]
changed the whole turn system
